// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.6.0.0
//      SpecFlow Generator Version:3.6.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NCS.DSS.FunctionalTests.Features.DigitalIdentity
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.6.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DigitalIdentityPatchV2")]
    public partial class DigitalIdentityPatchV2Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "PatchV2.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/DigitalIdentity", "DigitalIdentityPatchV2", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Patch a valid Digital Identity")]
        [NUnit.Framework.CategoryAttribute("digitalidentity")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        public virtual void PatchAValidDigitalIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "digitalidentity",
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Patch a valid Digital Identity", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table343 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table343.AddRow(new string[] {
                            "GivenName",
                            "Bob"});
                table343.AddRow(new string[] {
                            "FamilyName",
                            "Customer"});
                table343.AddRow(new string[] {
                            "PriorityGroups",
                            "1,3"});
#line 5
 testRunner.Given("I post a Customer with the following details V3:", ((string)(null)), table343, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table344 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table344.AddRow(new string[] {
                            "PreferredContactMethod",
                            "1"});
                table344.AddRow(new string[] {
                            "MobileNumber",
                            "07676 123456"});
                table344.AddRow(new string[] {
                            "HomeNumber",
                            "08654 123456"});
                table344.AddRow(new string[] {
                            "AlternativeNumber",
                            "07564656766"});
                table344.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612Z"});
#line 10
 testRunner.Given("I post a Contact with the following details with unique email address:", ((string)(null)), table344, "Given ");
#line hidden
#line 17
 testRunner.Then("there should be a 201 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table345 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table345.AddRow(new string[] {
                            "PreferredContactMethod",
                            "1"});
                table345.AddRow(new string[] {
                            "MobileNumber",
                            "07676 123456"});
                table345.AddRow(new string[] {
                            "HomeNumber",
                            "08654 123456"});
                table345.AddRow(new string[] {
                            "AlternativeNumber",
                            "07564656766"});
                table345.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612Z"});
#line 18
 testRunner.And("the response body should contain:", ((string)(null)), table345, "And ");
#line hidden
                TechTalk.SpecFlow.Table table346 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table346.AddRow(new string[] {
                            "IdentityStoreId",
                            "6973bf77-35f6-4989-a8ca-f1528d9c10a5"});
                table346.AddRow(new string[] {
                            "LegacyIdentity",
                            "07676 123456"});
                table346.AddRow(new string[] {
                            "id_token",
                            "08654 123456"});
                table346.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612+00:00"});
#line 25
 testRunner.Given("I Post a digital identity with the following details V2:", ((string)(null)), table346, "Given ");
#line hidden
#line 31
 testRunner.Then("there should be a 201 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table347 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table347.AddRow(new string[] {
                            "IdentityStoreId",
                            "6973bf77-35f6-4989-a8ca-f1528d9c10a5"});
                table347.AddRow(new string[] {
                            "LegacyIdentity",
                            "07676 123456"});
                table347.AddRow(new string[] {
                            "id_token",
                            "08654 123456"});
                table347.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612+00:00"});
#line 32
 testRunner.And("the response body should contain:", ((string)(null)), table347, "And ");
#line hidden
                TechTalk.SpecFlow.Table table348 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table348.AddRow(new string[] {
                            "id_token",
                            "1234567910"});
                table348.AddRow(new string[] {
                            "IdentityStoreId",
                            "aaf18eff-bf70-4e04-82ba-a056258f0db8"});
                table348.AddRow(new string[] {
                            "LegacyIdentity",
                            "\"test\""});
#line 38
 testRunner.Given("I patch the following digitalIdentity By CustomerId V2:", ((string)(null)), table348, "Given ");
#line hidden
#line 43
 testRunner.Then("there should be a 200 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table349 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table349.AddRow(new string[] {
                            "id_token",
                            "1234567910"});
                table349.AddRow(new string[] {
                            "IdentityStoreId",
                            "aaf18eff-bf70-4e04-82ba-a056258f0db8"});
                table349.AddRow(new string[] {
                            "LegacyIdentity",
                            "\"test\""});
#line 44
 testRunner.And("the response body should contain:", ((string)(null)), table349, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Patch Digital Identity for Customer that does not exist")]
        [NUnit.Framework.CategoryAttribute("digitalidentity")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        public virtual void PatchDigitalIdentityForCustomerThatDoesNotExist()
        {
            string[] tagsOfScenario = new string[] {
                    "digitalidentity",
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Patch Digital Identity for Customer that does not exist", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table350 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table350.AddRow(new string[] {
                            "id_token",
                            "1234567910"});
                table350.AddRow(new string[] {
                            "IdentityStoreId",
                            "aaf18eff-bf70-4e04-82ba-a056258f0db8"});
                table350.AddRow(new string[] {
                            "LegacyIdentity",
                            "\"test\""});
                table350.AddRow(new string[] {
                            "CustomerId",
                            "e432d40a-28bc-4969-bda8-9c096c747b52"});
#line 52
 testRunner.Given("I patch the following digitalIdentity By CustomerId V2:", ((string)(null)), table350, "Given ");
#line hidden
#line 58
 testRunner.Then("there should be a 422 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Patch a Digital Identity for a customer that does not have a digital identity")]
        [NUnit.Framework.CategoryAttribute("digitalidentity")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        public virtual void PatchADigitalIdentityForACustomerThatDoesNotHaveADigitalIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "digitalidentity",
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Patch a Digital Identity for a customer that does not have a digital identity", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table351 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table351.AddRow(new string[] {
                            "GivenName",
                            "Bob"});
                table351.AddRow(new string[] {
                            "FamilyName",
                            "Customer"});
                table351.AddRow(new string[] {
                            "PriorityGroups",
                            "1,3"});
#line 62
 testRunner.Given("I post a Customer with the following details V3:", ((string)(null)), table351, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table352 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table352.AddRow(new string[] {
                            "PreferredContactMethod",
                            "1"});
                table352.AddRow(new string[] {
                            "MobileNumber",
                            "07676 123456"});
                table352.AddRow(new string[] {
                            "HomeNumber",
                            "08654 123456"});
                table352.AddRow(new string[] {
                            "AlternativeNumber",
                            "07564656766"});
                table352.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612Z"});
#line 67
 testRunner.Given("I post a Contact with the following details with unique email address:", ((string)(null)), table352, "Given ");
#line hidden
#line 74
 testRunner.Then("there should be a 201 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table353 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table353.AddRow(new string[] {
                            "PreferredContactMethod",
                            "1"});
                table353.AddRow(new string[] {
                            "MobileNumber",
                            "07676 123456"});
                table353.AddRow(new string[] {
                            "HomeNumber",
                            "08654 123456"});
                table353.AddRow(new string[] {
                            "AlternativeNumber",
                            "07564656766"});
                table353.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612Z"});
#line 75
 testRunner.And("the response body should contain:", ((string)(null)), table353, "And ");
#line hidden
                TechTalk.SpecFlow.Table table354 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table354.AddRow(new string[] {
                            "id_token",
                            "1234567910"});
                table354.AddRow(new string[] {
                            "IdentityStoreId",
                            "aaf18eff-bf70-4e04-82ba-a056258f0db8"});
                table354.AddRow(new string[] {
                            "LegacyIdentity",
                            "\"test\""});
#line 82
 testRunner.Given("I patch the following digitalIdentity By CustomerId V2:", ((string)(null)), table354, "Given ");
#line hidden
#line 87
 testRunner.Then("there should be a 204 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Patch a valid Digital Identity By Digital IdentityId")]
        [NUnit.Framework.CategoryAttribute("digitalidentity")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        public virtual void PatchAValidDigitalIdentityByDigitalIdentityId()
        {
            string[] tagsOfScenario = new string[] {
                    "digitalidentity",
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Patch a valid Digital Identity By Digital IdentityId", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 90
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table355 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table355.AddRow(new string[] {
                            "GivenName",
                            "Bob"});
                table355.AddRow(new string[] {
                            "FamilyName",
                            "Customer"});
                table355.AddRow(new string[] {
                            "PriorityGroups",
                            "1,3"});
#line 91
 testRunner.Given("I post a Customer with the following details V3:", ((string)(null)), table355, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table356 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table356.AddRow(new string[] {
                            "PreferredContactMethod",
                            "1"});
                table356.AddRow(new string[] {
                            "MobileNumber",
                            "07676 123456"});
                table356.AddRow(new string[] {
                            "HomeNumber",
                            "08654 123456"});
                table356.AddRow(new string[] {
                            "AlternativeNumber",
                            "07564656766"});
                table356.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612Z"});
#line 96
 testRunner.Given("I post a Contact with the following details with unique email address:", ((string)(null)), table356, "Given ");
#line hidden
#line 103
 testRunner.Then("there should be a 201 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table357 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table357.AddRow(new string[] {
                            "PreferredContactMethod",
                            "1"});
                table357.AddRow(new string[] {
                            "MobileNumber",
                            "07676 123456"});
                table357.AddRow(new string[] {
                            "HomeNumber",
                            "08654 123456"});
                table357.AddRow(new string[] {
                            "AlternativeNumber",
                            "07564656766"});
                table357.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612Z"});
#line 104
 testRunner.And("the response body should contain:", ((string)(null)), table357, "And ");
#line hidden
                TechTalk.SpecFlow.Table table358 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table358.AddRow(new string[] {
                            "IdentityStoreId",
                            "6973bf77-35f6-4989-a8ca-f1528d9c10a5"});
                table358.AddRow(new string[] {
                            "LegacyIdentity",
                            "07676 123456"});
                table358.AddRow(new string[] {
                            "id_token",
                            "08654 123456"});
                table358.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612+00:00"});
#line 111
 testRunner.Given("I Post a digital identity with the following details V2:", ((string)(null)), table358, "Given ");
#line hidden
#line 117
 testRunner.Then("there should be a 201 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table359 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table359.AddRow(new string[] {
                            "IdentityStoreId",
                            "6973bf77-35f6-4989-a8ca-f1528d9c10a5"});
                table359.AddRow(new string[] {
                            "LegacyIdentity",
                            "07676 123456"});
                table359.AddRow(new string[] {
                            "id_token",
                            "08654 123456"});
                table359.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612+00:00"});
#line 118
 testRunner.And("the response body should contain:", ((string)(null)), table359, "And ");
#line hidden
                TechTalk.SpecFlow.Table table360 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table360.AddRow(new string[] {
                            "id_token",
                            "1234567910"});
                table360.AddRow(new string[] {
                            "IdentityStoreId",
                            "aaf18eff-bf70-4e04-82ba-a056258f0db8"});
                table360.AddRow(new string[] {
                            "LegacyIdentity",
                            "\"test\""});
#line 124
 testRunner.Given("I patch the following digitalIdentity By DigitalIdentityId V2:", ((string)(null)), table360, "Given ");
#line hidden
#line 129
 testRunner.Then("there should be a 200 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 130
 testRunner.And("there should be a record in the dss-digitalidentities table Ignoring \'\' with Iden" +
                        "tityId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table361 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table361.AddRow(new string[] {
                            "id_token",
                            "1234567910"});
                table361.AddRow(new string[] {
                            "IdentityStoreId",
                            "aaf18eff-bf70-4e04-82ba-a056258f0db8"});
                table361.AddRow(new string[] {
                            "LegacyIdentity",
                            "\"test\""});
#line 131
 testRunner.And("the response body should contain:", ((string)(null)), table361, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Patch a Digital Identity By Digital IdentityId for a customer that does not have " +
            "a digital identity")]
        [NUnit.Framework.CategoryAttribute("digitalidentity")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        public virtual void PatchADigitalIdentityByDigitalIdentityIdForACustomerThatDoesNotHaveADigitalIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "digitalidentity",
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Patch a Digital Identity By Digital IdentityId for a customer that does not have " +
                    "a digital identity", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 138
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table362 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table362.AddRow(new string[] {
                            "GivenName",
                            "Bob"});
                table362.AddRow(new string[] {
                            "FamilyName",
                            "Customer"});
                table362.AddRow(new string[] {
                            "PriorityGroups",
                            "1,3"});
#line 139
 testRunner.Given("I post a Customer with the following details V3:", ((string)(null)), table362, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table363 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table363.AddRow(new string[] {
                            "PreferredContactMethod",
                            "1"});
                table363.AddRow(new string[] {
                            "MobileNumber",
                            "07676 123456"});
                table363.AddRow(new string[] {
                            "HomeNumber",
                            "08654 123456"});
                table363.AddRow(new string[] {
                            "AlternativeNumber",
                            "07564656766"});
                table363.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612Z"});
#line 144
 testRunner.Given("I post a Contact with the following details with unique email address:", ((string)(null)), table363, "Given ");
#line hidden
#line 151
 testRunner.Then("there should be a 201 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table364 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table364.AddRow(new string[] {
                            "PreferredContactMethod",
                            "1"});
                table364.AddRow(new string[] {
                            "MobileNumber",
                            "07676 123456"});
                table364.AddRow(new string[] {
                            "HomeNumber",
                            "08654 123456"});
                table364.AddRow(new string[] {
                            "AlternativeNumber",
                            "07564656766"});
                table364.AddRow(new string[] {
                            "LastModifiedDate",
                            "2018-08-20T11:46:02.4482612Z"});
#line 152
 testRunner.And("the response body should contain:", ((string)(null)), table364, "And ");
#line hidden
                TechTalk.SpecFlow.Table table365 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table365.AddRow(new string[] {
                            "id_token",
                            "1234567910"});
                table365.AddRow(new string[] {
                            "IdentityStoreId",
                            "aaf18eff-bf70-4e04-82ba-a056258f0db8"});
                table365.AddRow(new string[] {
                            "LegacyIdentity",
                            "\"test\""});
#line 159
 testRunner.Given("I patch the following digitalIdentity By DigitalIdentityId V2:", ((string)(null)), table365, "Given ");
#line hidden
#line 164
 testRunner.Then("there should be a 204 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
